### ISSUE TITLE
Windows phone build issue

### ISSUE THREAD

**Issue by ThodorisElissaios** [apla/me.apla.cordova.app-preferences#118]
Issue:i cant build with phonegap build.
Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-app-preferences" via npm Installing "cordova-plugin-app-preferences" at "0.99.3" for windows Failed to install 'cordova-plugin-app-preferences':Error: Cannot find module 'cordova' at Function.Module._resolveFilename (module.js:337:15) at Function.Module._load (module.js:287:25) at Module.require (module.js:366:17) at require (module.js:385:17) at Context.requireCordovaModule (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\Context.js:77:12) at module.exports (C:\cygwin\tmp\gimlet\1086553\project\cordova\plugins\cordova-plugin-app-preferences\bin\lib\android.js:11:13) at module.exports (C:\cygwin\tmp\gimlet\1086553\project\cordova\plugins\cordova-plugin-app-preferences\bin\after_plugin_install.js:9:37) at runScriptViaModuleLoader (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:187:18) at runScript (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:165:16) at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pgb-plugman\node_modules\pgb-cordova-lib\src\hooks\HooksRunner.js:133:20 Cannot find module 'cordova'
_____

Please specify your environment

Plugin version:
  - [ ] released version: _____
  - [ ] repository master

Toolchain:
  - [ ] Cordova cli
  - [ ] Phonegap cli
  - [+] Phonegap cloud
  - [ ] Ionic
  - [ ] Other: _____

Platforms affected:
  - [ ] Android
  - [ ] iOS/macOS
  - [ ] LocalStorage fallback for browser and blackberry
  - [ ] Windows and Windows Phone 8.1 and later
  - [ ] Windows Phone 8 and earlier (deprecated)

What the scope of your problem:
  - [ ] General functionality (store/fetch/remove/clearAll)
  - [ ] Suites
  - [ ] Cloud synchronization and events
  - [ ] Preferences pane generation and display

**Comment by ThodorisElissaios** [comment]
anyone?
