### ISSUE TITLE
Add support for Cordova 9.0

### ISSUE THREAD

**Issue by jegesh** [apla/me.apla.cordova.app-preferences#147]
Issue:
When trying the install the plugin using Cordova v9.0, the following error is received:
```
Failed to install 'cordova-plugin-app-preferences': CordovaError: Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/path/to/project/plugins/cordova-plugin-app-preferences/bin/before_plugin_install.js:6:14)
```
`requireCordovaModule` has been removed in this version of Cordova.
 
Environment

Plugin version:
  - released version: 

Toolchain:
  - Cordova cli

Platforms affected:
  Probably all, only tried with iOs

What the scope of your problem:
  - Unable to install plugin

**Comment by NemSavic** [comment]
I had the same issue and was able to resolve. I created a pull request with my fix: https://github.com/apla/me.apla.cordova.app-preferences/pull/148

**Comment by lsbrandao** [comment]
I am having the same issue. I am trying to use this plugin with cordova v9.0, and I am receiving those errors as well.

> I had the same issue and was able to resolve. I created a pull request with my fix: #148

I tried using NemSavic's solution mentioned above, but "cordova.plugin.AppPreferences" is now undefined.

**Comment by sprengerst** [comment]
PUSH

**Comment by warrenonedge** [comment]
Is there any update on this?

**Comment by jorisbertomeu** [comment]
For my needs, I forked this project, done some fixes relative to cordova 9 (0.99.4) issue and to another Ionic issue (0.99.6) https://github.com/ionic-team/ionic-cli/issues/3014. Here is NPM package I published https://www.npmjs.com/package/@icscorp/cordova-plugin-app-preferences

**Comment by warrenonedge** [comment]
Thanks. This could be extremely helpful.

**Comment by mayursofbang4** [comment]
I am able to open the app preferences in IOS via _**Cordova plugin add https://github.com/myieye/me.apla.cordova.app-preferences**_ but not working in android. Can anyone have a solution for this issue? 

We are getting an error while clicking on the app preference icon - _**Class me.apla.cordova.AppPreferencesActivity not found. Please run preference generator.**_


[cordova plugin add https://github.com/myieye/me.apla.cordova.app-preferences](url)
