### ISSUE TITLE
Plugin add is broken for node 0.10.x

### ISSUE THREAD

**Issue by stefhenry** [apla/me.apla.cordova.app-preferences#63]
Hi,

I have phonegap 5.4.0 and cordova 5.3.7,
I am trying to add this plugin but I always get this error : 

sudo phonegap cordova plugin add cordova-plugin-app-preferences
Fetching plugin "cordova-plugin-app-preferences" via npm

Installing "cordova-plugin-app-preferences" for ios

Error during processing of action! Attempting to revert...

Failed to install 'cordova-plugin-app-preferences':TypeError: Uh oh!
Object #<Object> has no method 'parse'
    at module.exports.common.js-module.install (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:131:71)
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:653:27
    at Object.ActionStack.process (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PlatformApiPoly.addPlugin (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:259:20)
    at handleInstall (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:603:6)
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:509:49

Error: Uh oh!
Object #<Object> has no method 'parse'

thanks for your support,

Stéphane

**Comment by shredmer** [comment]
Try adding directly from the repo: cordova plugin add https://github.com/apla/me.apla.cordova.app-preferences

**Comment by stefhenry** [comment]
I tried but it's the same error message.

**Comment by stefhenry** [comment]
Which Cordova version are you using now ? Is there a specific version to use to make it compatible ?

Thanks,

**Comment by apla** [comment]
@stefhenry, cordova developers is ruined support for node 0.10.x, there is an issue: https://issues.apache.org/jira/browse/CB-9981 and pull request: https://github.com/apache/cordova-lib/pull/340. This issue not about this plugin, but cordova itself.

**Comment by stefhenry** [comment]
thank you so much @apla

**Comment by apla** [comment]
Pull request accepted, waiting for cordova tools release.

**Comment by apla** [comment]
Works fine with `node@0.10.x` and `cordova@5.4.1`
