### ISSUE TITLE
Error plug-in add for cordova 6

### ISSUE THREAD

**Issue by orlylevf** [apla/me.apla.cordova.app-preferences#78]
Hi
I am trying to add the plug-in in cordova 6 Android and get the flowing error:

Fetching plugin "cordova-plugin-app-preferences" via npm
Installing "cordova-plugin-app-preferences" for android
Failed to install 'cordova-plugin-app-preferences':TypeError: Uh oh!
Object #<Object> has no method 'parse'
    at handlers.js-module.install (C:\Dev\Cordova6\app\platforms\android\cordova\lib\pluginHandlers.js:142:66)
    at Object.ActionStack.process (C:\Dev\Cordova6\app\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at Api.addPlugin (C:\Dev\Cordova6\app\platforms\android\cordova\Api.js:205:20)
    at handleInstall (C:\Users\orly\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:601:6)
    at C:\Users\orly\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:385:28
    at _fulfilled (C:\Users\orly\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\orly\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\orly\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\orly\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\orly\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
Error: Uh oh!
Object #<Object> has no method 'parse'

There was old issue that resolved for cordova 5
Is there a fix for cordova 6?

**Comment by orlylev** [comment]
The issue solved using new node.js verion

**Comment by nikolasr200** [comment]
Fetching plugin "cordova-plugin-app-preferences" via npm
Error: Unexpected string

update to node js to latest but still problem

**Comment by apla** [comment]
@nikolasr200 please give more information. I've added automated testing to this project and I don't see any problems with cordova 6.0.0: https://travis-ci.org/apla/me.apla.cordova.app-preferences/builds/106931103

**Comment by nikolasr200** [comment]
The project was messed up after cordova upgrade to 5+ and i reinitiallized it. After that no problems faced

**Comment by apla** [comment]
@nikolasr200 issue with `Unexpected string` is fixed?

**Comment by nikolasr200** [comment]
Yes, it was fixed, so i dont think of it as plugin issue. Also upgraded node.js perhaps the combination of them brought the issue, but it was settled :) You ve done great job!!
